name: Trigger Workflow

inputs:
  params:
    description: 'A JSON representation of params need to be passed to the target workflow'
    required: false
    type: string
  target_repository:
    description: 'The repository org/name to trigger the workflow'
    required: true
    type: string
  target_workflow:
    description: 'The workflow name to be triggered'
    required: true
    type: string
  token:
    description: 'The GitHub Token to call GitHub API'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Delegate event to remote repository
      run: |
        curl -X POST \
          -H "Authorization: token ${{ inputs.token }}" \
          -d '${{ inputs.params }}' \
          https://api.github.com/repos/${{ inputs.target_repository }}/actions/workflows/${{ inputs.target_workflow }}/dispatches
