name: Trigger Workflow

inputs:
  params:
    description: 'A JSON representation of params need to be passed to the target workflow'
    required: false
    type: string
  target_repository:
    description: 'The repository org/name to trigger the workflow. Can be a comma separated string representation of an array'
    required: true
    type: string
  target_workflow:
    description: 'The workflow name to be triggered'
    required: true
    type: string
  token:
    description: 'The GitHub Token to call GitHub API'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Delegate event to remote repository
      shell: bash
      env:
        REPOSITORIES: ${{ inputs.target_repository }}
        PARAMS: ${{ inputs.params }}
      run: |
        PARAMS=${PARAMS//[$'\n']}
        PARAMS=${PARAMS//[$'"']/'\"'}
        
        echo "PARAMS=$PARAMS"
        
        for repo in ${REPOSITORIES//,/ }
        do
            echo " Calling https://api.github.com/repos/${repo}/actions/workflows/${{ inputs.target_workflow }}/dispatches with data=\"{\\\"inputs\\\": \\\"${PARAMS//[$'"']/'\"'}\\\"}\""
            
            result=$(curl -X POST \
              -H "Authorization: token ${{ inputs.token }}" \
              -d "{\"inputs\": ${PARAMS//[$'"']/'\"'}\"}" \
              https://api.github.com/repos/${repo}/actions/workflows/${{ inputs.target_workflow }}/dispatches)
            echo ${result}
            if [ ! "$(echo ${result} | grep -i '"message": "Not Found"')" ]; then
              echo 'Ok'
            else
              echo 'Failed'
            fi
        done

        
