name: Create or update PR

on:
  workflow_call:
    inputs:
      name:
        description: 'The PR name to update or create'
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR exist
      run: |
        id="$(gh pr list -L100 | cut -f1)"
        [ -n "$id" ] && gh pr checkout "$id"
