name: Create or update PR

inputs:
  name:
    description: 'The PR name to update or create'
    required: true
    type: string
  script:
    description: 'Commands you want to execute before creation or update of the new PR'
    required: false
    type: string
  token:
    description: 'The GitHub Token to call GitHub API'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check if PR exist
      shell: bash
      run: |
        gh auth login --with-token < <(echo "${{ inputs.token }}")
        
        PRs="$(gh pr list -L100 | cut -f1)"
        id=''
        for pr in $(echo ${PR}); do
          _id=$(echo "${PRs}" | cut -f1)
          _label=$(echo "${PRs}" | cut -f2)
          
          if [ "${_label}" == "${{ inputs.name }}" ]; then
            id=${_id}
            break
          fi
        done
        
        branch=''
        if [ -n "$id" ]; then
          branch="$(gh pr view "$id" --json headRefName --jq ".headRefName" | cat)"
          echo "$branch"
          git checkout "${branch}"
        else
          branch="$(echo "deps-bot/${{ inputs.name }}" |  tr '[:upper:]' '[:lower:]')"
          branch=${branch// /-}
          echo "$branch"
          git branch "${branch}"
          git checkout "${branch}"
        fi
        
        if [ -n "${{ inputs.scripts }}" ]; then
          echo "Running customization script"
          
          ${{ inputs.script }}
        fi
        
        git push
        
        info="$(gh pr view "$id" --json commits --jq ".commits[0].messageHeadline" | cat)"
        if [ -n "$id" ]; then
          gh pr comment "$id" -b "${info}"
        else
          gh pr create --title "${name}" --body "${info}"
        fi
