name: Create or update PR

inputs:
  name:
    description: 'The PR name to update or create'
    required: true
    type: string
  script:
    description: 'Commands you want to execute before creation or update of the new PR'
    required: true
    type: string
  token:
    description: 'The GitHub Token to call GitHub API'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check if PR exist
      shell: bash
      run: |
        gh auth login --with-token < <(echo "${{ inputs.token }}")
        git config user.email "github-bot@nocturlab.fr"
        git config user.name "github bot"
  
        PRs="$(gh pr list -L100)"
        id=''
        oldIFS=$IFS
        IFS="
        "; 
        for pr in $(echo ${PRs}); do
          _id=$(echo "${pr}" | cut -f1)
          _label=$(echo "${pr}" | cut -f2)
          
          if [ "${_label}" == "${{ inputs.name }}" ]; then
            id=${_id}
            break
          fi
        done
        IFS=$oldIFS
        
        branch=''
        if [ -n "$id" ]; then
          branch="$(gh pr view "$id" --json headRefName --jq ".headRefName" | cat)"
          git checkout "${branch}"
        else
          branch="$(echo "deps-bot/${{ inputs.name }}" |  tr '[:upper:]' '[:lower:]')"
          branch=${branch// /-}
          git checkout -b "${branch}"
        fi
        
        echo "Running customization script"

        ${{ inputs.script }}

        git show | cat
        
        
        
        if [ -n "$id" ]; then
          git push "${branch}"
          info="$(gh pr view "$id" --json commits --jq ".commits[0].messageHeadline" | cat)"
          gh pr comment "$id" -b "${info}"
        else
          git push -u origin "${branch}"
          info="$(git log --no-decorate --pretty=oneline -n 1 | cut -d" " -f2-)"
          gh pr create --title "${{ inputs.name }}" --body "${info}"
        fi
