name: Create or Update PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Dependency Version'
        required: true
      release_notes:
        description: 'DependencyRelease notes'
        required: false
      origin:
        description: 'Name of the dependency that has to be changed.'
        required: true

jobs:
  create_or_update_pr:
    name: Create or Update PR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup yq
        id: setup-yq
        uses: shiipou/setup-yq-action@v2.0.2
      - name: create_pr
        uses: ./create_or_update_pr
        with:
          name: 'Update dependecies'
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            yq eval ".dependencies.${{ github.event.inputs.origin }} = \"${{  github.event.inputs.version }}\"" -i project.yaml
            git add project.yaml
            
            RELEASE_NOTES="${{ github.event.inputs.release_notes }}"
            RELEASE_TYPE="${RELEASE_NOTES/:*}"
            
            git commit -m "${RELEASE_TYPE}: Upgrade ${{ github.event.inputs.origin }} to ${{ github.event.inputs.version }}
            ${RELEASE_NOTES}"
